Redis config cannot accept null values as the given example
PHPSocialNetwork/phpfastcache pull request #774
Opened 2020-11-26 11:30 UTC by GeoSot

## Proposed changes
According to this [example](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/examples/redis.php), password and database options can be nullable. 
```php

$InstanceCache = CacheManager::getInstance('redis', new Config([
  'host' => '127.0.0.1', //Default value
  'port' => 6379, //Default value
  'password' => null, //Default value
  'database' => null, //Default value
]));

```

For a given server setup I need these values to be null but, the Config setters didn't accept null values and thrown exception.

## Types of changes

What types of changes does your code introduce to Phpfastcache?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves an existing code/behavior)
- [ ] Deprecated third party dependency update
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation/Typo/Resource update that does not involve any code modification

## Agreement

I have read the [CONTRIBUTING](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CONTRIBUTING.md) and [CODING GUIDELINE](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CODING_GUIDELINE.md) docs

2020-11-26 23:10 UTC, Geolim4 requested changes
Hello,

Don't forget to also change the properties declarations and theirs annotation.

Thanks :)

2020-11-27 23:53 UTC, Geolim4 approved these changes

2020-11-27 23:54 UTC, merged

2020-11-30 09:40 UTC, GeoSot commented
@Geolim4 can you update the version, on packagist?

2020-11-30 10:30 UTC, Geolim4 commented
Hello,

Sadly I already updated the version last week (8.0.3) so you have to be patient until next month or use `dev-master` until the next release 👍🏼 

Cheers,
Georges.

2020-12-21 19:38 UTC, Geolim4 commented
[8.0.4 release](https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/8.0.4)  is out 😃