Refactor Redis driver to read all keys efficiently
PHPSocialNetwork/phpfastcache pull request #913
Opened 2024-06-07 10:21 UTC by mapcentia

The Redis driver's function to read all keys has been streamlined. The change is adding a loop to scan and merge the keys iteratively. This ensures that the function will work correctly, even when the number of keys scanned exceeds the MAX_ALL_KEYS_COUNT.

## Proposed changes

This is a fix for https://github.com/PHPSocialNetwork/phpfastcache/issues/912

## Types of changes

What types of changes does your code introduce to Phpfastcache?

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves an existing code/behavior)
- [ ] Deprecated third party dependency update
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation/Typo/Resource update that does not involve any code modification

## Agreement

I have read the [CONTRIBUTING](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CONTRIBUTING.md) and [CODING GUIDELINE](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CODING_GUIDELINE.md) docs

2024-06-08 23:12 UTC, Geolim4 commented
> The Redis driver's function to read all keys has been streamlined.
Where did you see that ? From which version ?
Backward compatibility **must be ensured** if this is a very recent change of Redis extension.

2024-06-10 12:37 UTC, mapcentia commented
I'm sorry for the not so good PR comment. By `Redis driver's function to read all keys` I mean the method ´driverReadAllKeys´ of lib/Phpfastcache/Drivers/Redis/Driver.php

2024-09-01 22:28 UTC, Geolim4 commented on lib/Phpfastcache/Drivers/Redis/Driver.php
> +            if (sizeof($keys) > ExtendedCacheItemPoolInterface::MAX_ALL_KEYS_COUNT) {
Use count instead of sizeof.

2024-09-01 22:28 UTC, Geolim4 commented on lib/Phpfastcache/Drivers/Redis/Driver.php
> +            $keys = array_merge($keys, $this->instance->scan($i, $pattern));
Do not use` array_merge` in loop due to performance issues.
See this thread:
https://dev.to/klnjmm/never-use-arraymerge-in-a-for-loop-in-php-5go1

Also please canonicalize php core functions:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CODING_GUIDELINE.md#php-core-functions

2024-09-01 22:29 UTC, Geolim4 requested changes
Please fix the points above

2024-09-17 19:34 UTC, mapcentia commented
It should be fixed. I've also made the same changed in the rediscluster driver

2024-09-17 19:41 UTC, Geolim4 commented
Hello, thanks but the quality tools does not pass, please run them locally before pushing:

https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CONTRIBUTING.md#developer-notes

2024-11-27 19:12 UTC, Geolim4 commented
Can you fix the CI @mapcentia ?
Just fix Github actions, don't pay attention to Travis which will be removed soon !

2025-01-29 18:06 UTC, mapcentia commented on .github/workflows/testsv2.yml
> -        operating-system: [ubuntu-latest]
Using 'latest' now resolves to 24.04, which makes the installation of packages fail

2025-01-29 18:08 UTC, Geolim4 commented on .github/workflows/testsv2.yml
> -        operating-system: [ubuntu-latest]
I agree distro should not get upgraded.

2025-03-02 13:47 UTC, Geolim4 commented
thank you !

2025-03-02 13:47 UTC, merged